// Code generated by hertz generator.

package chat

import (
	"Hertz_refactored/biz/mv"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chatMw() []app.HandlerFunc {
	// your code...
	/*	return []app.HandlerFunc{
		mv.JwtMiddleware.MiddlewareFunc(),
	}*/
	return nil
}

func _chatsMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.JwtMiddleware.MiddlewareFunc(),
	}
}
