version: '3'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: hertz_mysql
    volumes:
      - ./biz/config/mysql.sql:/docker-entrypoint-initdb.d
      - ./biz/pkg/data/sql:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    privileged: true
    environment:
      - MYSQL_DATABASE=hertz
      - MYSQL_USER=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - docker_net

  redis:
    image: redis:6
    container_name: hertz_redis
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - ./biz/pkg/data/redis/:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - docker_net

  rabbitmq:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq
    ports:
      - ${RABBIT_MQ_PORT}:5672
      - ${RABBIT_MQ_M_PORT}:15672
    environment:
      - TZ=${RABBIT_MQ_TZ}
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASS}
    volumes:
      - ./biz/pkg/data/rabbitmq:/var/lib/rabbitmq
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge
