version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: hertz_mysql
    volumes:
      - ./biz/config/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    privileged: true
    environment:
      - MYSQL_DATABASE=hertz
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - docker_net

  redis:
    image: redis:latest
    container_name: hertz_redis
    ports:
      - "6379:6379"
    volumes:
      - ./biz/dal/cache/redis/redis.conf:/usr/local/etc/redis/redis.conf  
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - docker_net

  rabbitmq:
    image: rabbitmq:3.8.5-management
    container_name: rabbitmq_test
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - docker_net

  work:
    image: work:latest
    container_name: work_main
    depends_on:
      - mysql
      - redis
      - rabbitmq
    profiles: 
    - release
    ports:
      - 8000:8888
    networks:
      - docker_net

networks:
  docker_net:
    driver: bridge
