// Code generated by hertz generator.

package main

import (
	chats "Hertz_refactored/biz/dal/db/chats/im"
	"Hertz_refactored/biz/dal/mongodb"
	"Hertz_refactored/biz/dal/mysql"
	"Hertz_refactored/biz/dal/redis"
	"Hertz_refactored/biz/mv"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	mysql.Init()
	mongodb.Init()
	redis.Init()
	mv.InitJwt()
	h := server.Default(
		server.WithStreamBody(true),
		server.WithMaxRequestBodySize(16*1024*1024))
	h.NoHijackConnPool = true
	go chats.Manager.Listen()
	register(h)
	h.Spin()
}

/*
这是一些额外的默认配置项的修改
server.WithHostPorts("127.0.0.1:8080")：设置服务器的监听地址和端口为 127.0.0.1:8080。默认情况下，Hertz 服务器监听在端口 8888，通过这个选项可以修改监听的地址和端口。
server.WithMaxRequestBodySize(20<<20)：设置请求体的最大限制为 20MB。这个选项可以控制接收请求时的最大请求体大小，当请求体超过设置的限制时，服务器会返回 413 Request Entity Too Large 状态码。
server.WithTransport(standard.NewTransporter)：使用标准的 HTTP 传输器。Hertz 提供了多种传输器，例如标准的 HTTP 传输器、Fasthttp 传输器等。通过该选项可以选择使用不同的传输器来处理请求。
*/
