// Code generated by hertz generator.

package comment

import (
	"Hertz_refactored/biz/mv"
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.JwtMiddleware.MiddlewareFunc(),
	}
}

func _deletecommentMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.JwtMiddleware.MiddlewareFunc(),
	}
}

func _listcommentMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		mv.JwtMiddleware.MiddlewareFunc(),
	}
}

func _createcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}
