// Code generated by hertz generator.

package comment

import (
	comment2 "Hertz_refactored/biz/dal/db/comment"
	"Hertz_refactored/biz/model/comment"
	"Hertz_refactored/biz/pkg/errno"
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"time"
)

// CreateComment .
// @router /v1/comment/publish [POST]
func CreateComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req comment.CreateCommentRequest
	err = c.BindAndValidate(&req)
	userId, _ := c.Get("user_id")
	resp := new(comment.CreateCommentResponse)
	if uid, ok := userId.(float64); ok {
		if err != nil {
			c.String(consts.StatusBadRequest, err.Error())
			return
		}
		comments := &comment.Comment{
			VideoId: req.VideoId,
			Comment: req.Comment,
			UserId:  int64(uid),
			Time:    time.Now().Format(time.DateTime),
		}
		if err := comment2.CreateComment(comments); err != nil {
			panic(err)
		}
		resp.Code = consts.StatusOK
		resp.Msg = "创建评论成功"
		c.JSON(consts.StatusOK, resp)
		return
	}
	resp.Code = consts.StatusBadRequest
	resp.Msg = "创建评论失败"
	c.JSON(consts.StatusBadRequest, resp)
	return
}

// ListComment .
// @router /v1/comment/list [GET]
func ListComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req comment.ListCommentRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	var comments []*comment.Comment
	var total int64
	userId, _ := c.Get("user_id")
	if uid, ok := userId.(float64); ok {
		comments, total, err = comment2.ListComment(req, int64(uid))
		if err != nil {
			panic(err)
		}
		c.JSON(consts.StatusOK, &comment.ListCommentResponse{
			Code:     errno.SuccessCode,
			Msg:      "展示评论信息",
			Comments: comments,
			Total:    total,
		})
		return
	}
	c.JSON(consts.StatusBadRequest, "展示评论列表失败")
	return
}

// DeleteComment .
// @router /v1/comment/delete [DELETE]
func DeleteComment(ctx context.Context, c *app.RequestContext) {
	var err error
	var req comment.CommentDeleteRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	if err := comment2.DeleteComment(req); err != nil {
		panic(err)
	}
	resp := new(comment.CommentDeleteResponse)
	resp.Code = consts.StatusOK
	resp.Msg = "成功删除一条记录"
	c.JSON(consts.StatusOK, resp)
}
