FROM golang:1.21-alpine AS builder

COPY biz/ /go/src/biz/
COPY go.mod go.sum *.go /go/src/

ENV GO111MODULE=on \
    GOOS=linux \
    FOARCH=amd64 \
    GOPROXY=https://goproxy.cn,direct

WORKDIR /go/src
RUN go mod tidy
RUN go build -o test

FROM alpine:latest
COPY --from=builder /go/src/test /app/
WORKDIR /app
CMD [ "./test" ]