// Code generated by hertz generator.

package publish

import (
	"Hertz_refactored/biz/router/authfunc"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _videoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadvideoMw() []app.HandlerFunc {
	return authfunc.Auth()
}
