// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	chat "Hertz_refactored/biz/router/chat"
	comment "Hertz_refactored/biz/router/comment"
	favorite "Hertz_refactored/biz/router/favorite"
	publish "Hertz_refactored/biz/router/publish"
	relation "Hertz_refactored/biz/router/relation"
	user "Hertz_refactored/biz/router/user"
	video "Hertz_refactored/biz/router/video"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	chat.Register(r)

	relation.Register(r)

	user.Register(r)

	favorite.Register(r)

	publish.Register(r)

	video.Register(r)

	comment.Register(r)

}
